[package]
name    = "nyquist-perf"
version = "0.1.0"
edition = "2021"

[dependencies]
nyquist-core = { path = "../nyquist-core" }
async-trait  = "0.1"
tracing      = "0.1"
thiserror    = "1"

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = "0.4"
libc       = "0.2"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
