[package]
name = "nyquist-samplers"
version.workspace = true
edition.workspace = true

[dependencies]
nyquist-core = { workspace = true }
linkme = { workspace = true }
nyquist-sysconfig = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
libc = { workspace = true }
