[package]
name = "nyquist-syswatch"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
nyquist-core = { workspace = true }
nyquist-sysconfig = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "sync"] }
clickhouse = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libbpf-rs = { workspace = true }
libc = { workspace = true }

[target.'cfg(target_os = "linux")'.build-dependencies]
libbpf-cargo = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
