[package]
name = "nyquist-clickhouse"
version.workspace = true
edition.workspace = true

[dependencies]
nyquist-core = { workspace = true }
nyquist-sysconfig = { workspace = true }
clickhouse = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }

[dev-dependencies]
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

