[package]
name = "nyquist-ebpf"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
nyquist-core = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
linkme = { workspace = true }
histogram = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libbpf-rs = { workspace = true }
memmap2 = { workspace = true }
libc = { workspace = true }

[target.'cfg(target_os = "linux")'.build-dependencies]
libbpf-cargo = { workspace = true }
