[package]
name = "nyquist-ebpf-programs"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "nyquist-ebpf-programs"
path = "src/main.rs"

[dependencies]
aya-ebpf = "0.1"
nyquist-ebpf-common = { path = "../nyquist-ebpf-common" }

[profile.dev]
panic = "abort"
opt-level = 2

[profile.release]
panic = "abort"
lto = true
opt-level = 3
