[package]
name = "nyquist-core"
version.workspace = true
edition.workspace = true

[dependencies]
histogram = { workspace = true }
linkme = { workspace = true }
dashmap = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros", "sync"] }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros", "test-util"] }
